### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elie-chaaban** [glyphard/expo-server-sdk-dotnet#4]
The push api client is stuck in this line:

 await _httpClient.PostAsync(path, requestBody);

**Comment by tinvo92** [comment]
I have a same problem. is there anyone has idea.???

**Comment by jeremy-farrance** [comment]
Same problem here, weirdly if you let it sit, it times out after 2+ mins and it DOES the send/push. Not very useful though.

**Comment by glyphard** [comment]
@elie-chaaban @jeremy-farrance that is odd, can you share a simple repro that includes the calling code?  I'll take a look.

**Comment by fangot14** [comment]
I have the same problem with the following line:
var result = expoSDKClient.PushSendAsync(pushTicketReq).GetAwaiter().GetResult();
This line comes from the example given on this page:
https://github.com/glyphard/expo-server-sdk-dotnet

**Comment by glyphard** [comment]
@jeremy-farrance Ahh, ok just updated the read.me example to make the call fully async via await keywrod.  Let me know if that solves the issue for you.

**Comment by glyphard** [comment]
Have updated the read.me   If you are still experiencing a problem with it, please re-open this issue.
